/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PhepTinh_UI.java
 *
 * Created on Sep 15, 2022, 3:57:21 PM
 */
package pheptinh_UI;

import java.awt.event.KeyEvent;
import javax.swing.JTextField;

/**
 *
 * @author HP
 */
public class PhepTinh_UI extends javax.swing.JFrame {

    /** Creates new form PhepTinh_UI */
    public PhepTinh_UI() {
        initComponents();
        txtInput1.setText("");
        txtInput2.setText("");
        txtResult.setText("");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtInput1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSumbit = new javax.swing.JButton();
        txtResult = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtInput2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cboToanTu = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtInput1.setText("5");
        txtInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInput1ActionPerformed(evt);
            }
        });
        txtInput1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInput1KeyPressed(evt);
            }
        });

        jLabel1.setText("Toán hạng 1:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Két quả n!");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnSumbit.setText("Tính toán");
        btnSumbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumbitActionPerformed(evt);
            }
        });

        txtResult.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtResult.setText("12.0");
        txtResult.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel3.setText("Toán hạng 2:");

        txtInput2.setText("5");
        txtInput2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInput2ActionPerformed(evt);
            }
        });
        txtInput2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInput2KeyPressed(evt);
            }
        });

        jLabel4.setText("Toán tử:");

        cboToanTu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-", "*", "/", "%", "^" }));
        cboToanTu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboToanTuKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(39, 39, 39)
                        .addComponent(cboToanTu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtResult))
                        .addComponent(btnSumbit)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(txtInput2))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(txtInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cboToanTu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(btnSumbit)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtResult))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean IsNumber(JTextField txtInput){
            String input = txtInput.getText();
            for(int i=0;i<input.length();i++){
                if(input.charAt(i)==45 && i==0)
                    continue;
                if(input.charAt(i)>57 || input.charAt(i)<48)
                    return false;
            }
            return txtInput.getText().length()>0;
        }
    private void txtInput1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInput1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            txtInput2.requestFocus();
}//GEN-LAST:event_txtInput1KeyPressed

    private void btnSumbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumbitActionPerformed
        // TODO add your handling code here:
        if(IsNumber(txtInput1)&&IsNumber(txtInput2)){
            int n1 = Integer.parseInt(txtInput1.getText());
            int n2 = Integer.parseInt(txtInput2.getText());
            char n3 = cboToanTu.getSelectedItem().toString().charAt(0);
            PhepTinh pt = new PhepTinh(n1, n2, n3);
            txtResult.setText(String.valueOf(pt.tinhToan()));
        } else if(IsNumber(txtInput1))
            txtResult.setText("Input 2 invalid!");
        else
            txtResult.setText("Input 1 invalid!");
}//GEN-LAST:event_btnSumbitActionPerformed

    private void txtInput2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInput2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            btnSumbitActionPerformed(null);
    }//GEN-LAST:event_txtInput2KeyPressed

    private void txtInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInput1ActionPerformed

    private void txtInput2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInput2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInput2ActionPerformed

    private void cboToanTuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboToanTuKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            btnSumbitActionPerformed(null);
    }//GEN-LAST:event_cboToanTuKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PhepTinh_UI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSumbit;
    private javax.swing.JComboBox cboToanTu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtInput1;
    private javax.swing.JTextField txtInput2;
    private javax.swing.JLabel txtResult;
    // End of variables declaration//GEN-END:variables
}
